# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-06-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socionic_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=3)),
                ('symbol_dif', models.CharField(default='', max_length=4)),
                ('name', models.CharField(default='', max_length=50)),
                ('name_dif', models.CharField(default='', max_length=50)),
                ('quadra', models.CharField(default='', max_length=15)),
                ('img_soc', models.ImageField(upload_to='sociotypetest/static/img_soc')),
                ('img_description', models.CharField(default='none', max_length=200)),
                ('description_short', models.TextField(default='none', max_length=5000)),
                ('description', models.TextField(default='none', max_length=10000)),
                ('dichotomies', models.TextField(default='none', max_length=10000)),
            ],
        ),
    ]
