# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-06-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней активности'),
        ),
    ]
