# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-06-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalp', '0002_auto_20170630_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
